/* Exercises real UI and existing DEV fixture IDs. All saves are callback-only. */
const fs = require('node:fs');
const path = require('node:path');
const { chromium } = require(process.env.PLAYWRIGHT_MODULE || 'playwright');
const origin = process.argv[2] || 'http://127.0.0.1:5191';
const output = path.resolve('docs/validation/commission-workspace/after');
fs.mkdirSync(output,{recursive:true});
const results = { checks: [], errors: [], fixtureBoundary:'Existing DEV fixture IDs, callback-only saves; no Supabase requests or writes' };
const check = (name,passed,detail) => { results.checks.push({name,passed,detail});console.log(JSON.stringify(results.checks.at(-1))); };

(async()=>{
  const browser = await chromium.launch({headless:true,channel:'chrome'});
  const page = await browser.newPage({viewport:{width:1366,height:768},locale:'pt-BR',reducedMotion:'reduce'});
  page.on('pageerror',error=>results.errors.push(error.message));
  const goto = async(params) => {
    await page.goto(`${origin}/__dev/comissao-agenda/agenda?${new URLSearchParams({tab:'agenda',unit:'acolhimento-e-bem-comum',...params})}`,{waitUntil:'commit'});
    await page.locator('.ua-page').waitFor();
  };
  await goto({});
  await page.locator('.ua-search input').fill('1ª Reunião Geral');
  const card = page.locator('.ua-event-card').first();
  const peopleTrigger = card.getByRole('button',{name:/Ver 6 pessoas responsáveis/});
  await peopleTrigger.click();
  const popup = page.getByRole('dialog',{name:'Pessoas responsáveis',exact:true});
  await popup.waitFor();
  check('People +N reveals all six fixture responsible names',await popup.locator('li').count()===6);
  await page.screenshot({path:path.join(output,'desktop-responsibles-popover.png')});
  await page.keyboard.press('Escape');
  await popup.waitFor({state:'hidden'});
  check('People +N Escape returns focus to trigger',await peopleTrigger.evaluate(el=>el===document.activeElement));
  const unitsTrigger = card.getByRole('button',{name:/Ver todas as 4 comissões/});
  await unitsTrigger.click();
  const unitsPopup = page.getByRole('dialog',{name:'Comissões e assessorias vinculadas',exact:true});
  await unitsPopup.waitFor();
  check('Fronts +N reveals all four existing unit names',await unitsPopup.locator('li').count()===4);
  await page.screenshot({path:path.join(output,'desktop-fronts-popover.png')});
  await page.keyboard.press('Escape');
  await unitsPopup.waitFor({state:'hidden'});
  check('Fronts +N Escape returns focus to trigger',await unitsTrigger.evaluate(el=>el===document.activeElement));
  await goto({open:'ev-06'});
  await page.getByRole('dialog').waitFor();
  await page.getByRole('button',{name:'Editar',exact:true}).click();
  const original = await page.evaluate(()=>window.__commissionQaFixtures.find(event=>event.id==='ev-06'));
  const originalTitle = await page.getByLabel('Título',{exact:false}).inputValue();
  const people = page.locator('.ua-relation').filter({has:page.getByText('Pessoas responsáveis',{exact:true})});
  const selectedNames = await people.locator('.ua-relation__selected .ua-relation__option-copy .ws-meta').allTextContents();
  check('Editing starts with canonical principal first', selectedNames[0] === original.people[0].name, selectedNames);
  const title = page.getByLabel('Título',{exact:false});
  await title.fill(`${originalTitle} — revisão visual`);
  await people.getByRole('button',{name:/Pessoas responsáveis Buscar e selecionar/}).click();
  const search = page.getByLabel('Buscar em pessoas responsáveis',{exact:true});
  await search.pressSequentially('Marina',{delay:35});
  check('Search retains focus throughout typing', await search.evaluate(el=>el===document.activeElement) && await search.inputValue()==='Marina');
  check('Opening selector retains edited title',await title.inputValue()===`${originalTitle} — revisão visual`);
  await search.press('ArrowDown');
  check('Keyboard reaches matching choice',await page.getByRole('checkbox',{name:/Marina Ribeiro/}).evaluate(el=>el===document.activeElement));
  await page.keyboard.press('Space');
  await page.keyboard.press('Escape');
  check('Selector Escape restores trigger without closing event', await page.getByRole('dialog').count()===1 && await people.getByRole('button',{name:/Pessoas responsáveis Buscar e selecionar/}).evaluate(el=>el===document.activeElement));
  await people.getByRole('button',{name:'Remover Roberto Steffen',exact:true}).click();
  await page.screenshot({path:path.join(output,'desktop-edit-selection.png')});
  await page.getByRole('button',{name:'Salvar alterações',exact:true}).click();
  const submitted = await page.evaluate(()=>window.__commissionQaSubmission);
  const expectedPeople = original.people.map(person=>person.id).filter(id=>id!=='p-roberto').concat('p-marina');
  check('Edit submits unchanged canonical event ID',submitted?.editingId==='ev-06',submitted?.editingId);
  check('Edit preserves people ID order and principal',JSON.stringify(submitted?.draft.peopleIds)===JSON.stringify(expectedPeople),submitted?.draft.peopleIds);
  check('Edit preserves existing ordered unit IDs',JSON.stringify(submitted?.draft.unitIds)===JSON.stringify(original.units.map(unit=>unit.id)),submitted?.draft.unitIds);
  check('Edit retains original date and times',submitted?.draft.date===original.date&&submitted?.draft.startTime===original.startTime&&submitted?.draft.endTime===original.endTime);

  await goto({open:'create'});
  await page.getByRole('dialog').waitFor();
  await page.getByLabel('Título',{exact:false}).fill('Reunião de preparação da frente');
  await page.locator('.ua-form input[type="date"]').first().fill('2026-10-24');
  const createPeople = page.locator('.ua-relation').filter({has:page.getByText('Pessoas responsáveis',{exact:true})});
  await createPeople.getByRole('button',{name:/Pessoas responsáveis Buscar e selecionar/}).click();
  await page.getByLabel('Buscar em pessoas responsáveis',{exact:true}).fill('Raul');
  await page.getByRole('checkbox',{name:/Raul Dário/}).check();
  await page.getByLabel('Buscar em pessoas responsáveis',{exact:true}).fill('Bruna');
  await page.getByRole('checkbox',{name:/Bruna Pacheco/}).check();
  await page.getByLabel('Buscar em pessoas responsáveis',{exact:true}).fill('');
  for(const checkbox of await createPeople.getByRole('checkbox').all()) if(!(await checkbox.isChecked())) await checkbox.check();
  await page.keyboard.press('Escape');
  const names = await createPeople.locator('.ua-relation__selected .ua-relation__option-copy .ws-meta').allTextContents();
  check('Many selections preserve chosen principal without alphabetic reorder',names.length===14&&names[0]==='Raul Dário Nunez'&&names[1]==='Bruna Pacheco de Quadros',names);
  const participants = page.locator('.ua-relation').filter({has:page.getByText('Comissões e assessorias participantes',{exact:true})});
  await participants.getByRole('button',{name:/Comissões e assessorias participantes Buscar e selecionar/}).click();
  await page.getByLabel('Buscar em comissões e assessorias participantes',{exact:true}).fill('Imprensa');
  await page.getByRole('checkbox',{name:/Assessoria de Imprensa/}).check();
  await page.keyboard.press('Escape');
  await page.setViewportSize({width:390,height:844});
  await createPeople.scrollIntoViewIfNeeded();
  await page.screenshot({path:path.join(output,'mobile-fourteen-responsibles.png')});
  const footer = await page.locator('.ua-form__footer').boundingBox();
  check('Mobile form actions stay visible during long selections',footer.y>=0&&footer.y+footer.height<=844,{footer});
  await page.getByRole('dialog').getByRole('button',{name:'Criar evento',exact:true}).click();
  const createSubmitted = await page.evaluate(()=>window.__commissionQaSubmission);
  check('Create preserves initial principal ID and all14 people',createSubmitted?.draft.peopleIds[0]==='p-raul'&&createSubmitted?.draft.peopleIds.length===14,createSubmitted?.draft.peopleIds);
  check('Create retains required workspace unit and participant',JSON.stringify(createSubmitted?.draft.unitIds)===JSON.stringify(['acolhimento-e-bem-comum','assessoria-de-imprensa']),createSubmitted?.draft.unitIds);

  for(const width of [320,390,1366]) {
    await page.setViewportSize({width,height:width===1366?768:844});
    await goto({open:'create',unit:'assessoria-de-relacoes-internacionais'});
    await page.getByRole('dialog').waitFor();
    const box = await page.getByRole('dialog').boundingBox();
    const actions = await page.locator('.ua-form__footer').boundingBox();
    check(`Long-name form fits ${width}px and actions remain visible`,box.x>=0&&box.x+box.width<=width+1&&actions.y+actions.height<=(width===1366?768:844)+1,{box,actions});
    if(width===320) await page.screenshot({path:path.join(output,'320-long-advisory-form.png')});
    await page.getByLabel('Título',{exact:false}).fill('ab');
    await page.locator('.ua-form textarea').focus();
    check(`Title error adjacent and labelled at${width}px`,await page.getByRole('alert').count()>=1&&await page.getByLabel('Título',{exact:false}).getAttribute('aria-invalid')==='true');
    await page.getByRole('button',{name:'Cancelar',exact:true}).click();
    await page.getByRole('dialog').waitFor({state:'hidden'});
    check(`Cancel closes form at${width}px`,await page.getByRole('dialog').count()===0);
  }
  await page.setViewportSize({width:390,height:480});
  await goto({open:'create'});
  await page.getByRole('dialog').waitFor();
  await page.getByLabel('Título',{exact:false}).focus();
  const keyboardFooter = await page.locator('.ua-form__footer').boundingBox();
  check('Form actions fit shortened480px viewport (keyboard approximation)',keyboardFooter.y>=0&&keyboardFooter.y+keyboardFooter.height<=481,keyboardFooter);
  await page.screenshot({path:path.join(output,'mobile-480px-form.png')});
  await page.setViewportSize({width:390,height:844});
  await goto({});
  const createTrigger = page.getByRole('button',{name:'Criar evento',exact:true});
  for(const exit of ['Cancelar','Fechar','Escape']) {
    await createTrigger.click();
    await page.getByRole('dialog').waitFor();
    if(exit==='Escape') await page.keyboard.press('Escape');
    else await page.getByRole('button',{name:exit,exact:true}).click();
    await page.getByRole('dialog').waitFor({state:'hidden'});
    check(`Create ${exit} returns focus to opener`,await createTrigger.evaluate(el=>el===document.activeElement));
  }
  const eventTrigger = page.locator('.ua-event-card').first().getByRole('button',{name:'Ver evento',exact:true});
  await eventTrigger.click();
  await page.getByRole('dialog').waitFor();
  await page.getByRole('button',{name:'Editar',exact:true}).click();
  await page.locator('.ua-form').waitFor();
  await page.getByRole('button',{name:'Cancelar',exact:true}).click();
  await page.getByRole('dialog').waitFor({state:'hidden'});
  check('Detail → edit → cancel returns focus to original event opener',await eventTrigger.evaluate(el=>el===document.activeElement));
  await browser.close();
})().catch(error=>{results.errors.push(error.stack);console.error(error);process.exitCode=1;}).finally(()=>{
  fs.writeFileSync(path.join(output,'interaction-results.json'),JSON.stringify(results,null,2));process.exit(process.exitCode||0);
});
