const fs=require('node:fs');const assert=require('node:assert/strict');
const {PGlite}=require(process.env.PGLITE_MODULE||'@electric-sql/pglite');
const migration=fs.readFileSync('supabase/migrations/20260908010000_soy_restroom_gate9_infrastructure.sql','utf8');
const baseline=JSON.parse(fs.readFileSync('docs/screenshots/soy-gate9/before-inventory.json','utf8')).entities;
const schema=`CREATE TABLE map_projects(id uuid PRIMARY KEY DEFAULT gen_random_uuid(), is_archived boolean DEFAULT false,reference_revision text);
CREATE TABLE map_layers(id uuid PRIMARY KEY DEFAULT gen_random_uuid(),project_id uuid REFERENCES map_projects(id),layer_key text,UNIQUE(project_id,layer_key));
CREATE TABLE map_entities(id uuid PRIMARY KEY DEFAULT gen_random_uuid(),project_id uuid REFERENCES map_projects(id),layer_id uuid REFERENCES map_layers(id),public_identifier text,name text,description text,classification text,verification_status text,is_sellable boolean,is_archived boolean,metadata jsonb,updated_at timestamptz DEFAULT now(),UNIQUE(project_id,public_identifier));
CREATE TABLE map_entity_geometries(id uuid PRIMARY KEY DEFAULT gen_random_uuid(),project_id uuid REFERENCES map_projects(id),entity_id uuid REFERENCES map_entities(id),geometry jsonb,elevation numeric,extrusion_height numeric,rotation numeric,version integer,is_current boolean,change_reason text,UNIQUE(entity_id,version));
CREATE UNIQUE INDEX one_current ON map_entity_geometries(entity_id) WHERE is_current;
CREATE TABLE commercial_lots(id uuid PRIMARY KEY DEFAULT gen_random_uuid(),entity_id uuid REFERENCES map_entities(id),price numeric);`;
async function fixture(conflict=false,offset=false){const db=new PGlite();await db.exec(schema);const {rows:[project]}=await db.query("INSERT INTO map_projects(reference_revision) VALUES('2026.4') RETURNING id");const layers={};for(const key of ['pavilions','gates','restrooms','structures','circulation','commercial']) {layers[key]=(await db.query('INSERT INTO map_layers(project_id,layer_key) VALUES($1,$2) RETURNING id',[project.id,key])).rows[0].id;}
 for(const code of ['B7','A9','E-07','B28','Q-D-11']){const e=baseline.find(e=>e.publicIdentifier===code);const {rows:[row]}=await db.query('INSERT INTO map_entities(project_id,layer_id,public_identifier,name,description,classification,verification_status,is_sellable,is_archived,metadata) VALUES($1,$2,$3,$4,$5,$6,$7,$8,$9,$10) RETURNING id',[project.id,layers[e.layerId.replace('reference:','')],code,e.name,e.description,e.classification,e.verificationStatus,e.isSellable,code==='E-07',e.metadata]);const geometry={type:'Polygon',coordinates:structuredClone(e.geometry.coordinates)};if(offset&&code==='B7')geometry.coordinates[0][0][0]+=5;await db.query('INSERT INTO map_entity_geometries(project_id,entity_id,geometry,elevation,extrusion_height,rotation,version,is_current,change_reason) VALUES($1,$2,$3,0,$4,0,1,true,\'baseline\')',[project.id,row.id,geometry,e.geometry.extrusionHeight]);if(code==='Q-D-11'||(conflict&&code==='E-07'))await db.query('INSERT INTO commercial_lots(entity_id,price) VALUES($1,12345)',[row.id]);}
 return db;}
(async()=>{const checks={};let db=await fixture();try{const unrelated=await db.query("SELECT * FROM map_entities WHERE public_identifier<>'E-07' ORDER BY public_identifier");const lots=await db.query('SELECT * FROM commercial_lots');await db.exec(migration);checks.exactlyTwoNewEntities=(await db.query('SELECT count(*)::int n FROM map_entities')).rows[0].n===7;checks.historyRetained=(await db.query("SELECT count(*)::int n FROM map_entity_geometries g JOIN map_entities e ON e.id=g.entity_id WHERE e.public_identifier='E-07'")).rows[0].n===2;checks.restroomReactivated=(await db.query("SELECT is_archived FROM map_entities WHERE public_identifier='E-07'")).rows[0].is_archived===false;assert.deepEqual((await db.query('SELECT * FROM commercial_lots')).rows,lots.rows);checks.commercialRecordsPreserved=true;assert.deepEqual((await db.query("SELECT * FROM map_entities WHERE public_identifier NOT IN ('E-07','RES-A9','RUA-MONTEVIDEU-COZINHA') ORDER BY public_identifier")).rows,unrelated.rows);checks.neighborsPreserved=true;const once=await db.query('SELECT * FROM map_entity_geometries ORDER BY id');await db.exec(migration);assert.deepEqual((await db.query('SELECT * FROM map_entity_geometries ORDER BY id')).rows,once.rows);checks.idempotent=true;}finally{await db.close();}
 db=await fixture(true);try{let error;try{await db.exec(migration)}catch(e){error=e.message;await db.exec('ROLLBACK');}checks.salesConflictRefused=!!error?.includes('Infrastructure identity conflict');checks.atomicRollback=(await db.query('SELECT count(*)::int n FROM map_entities')).rows[0].n===5;}finally{await db.close();}
 db=await fixture(false,true);try{await db.exec(migration);checks.foreignCoordinateFrameUntouched=(await db.query('SELECT count(*)::int n FROM map_entities')).rows[0].n===5;}finally{await db.close();}
 fs.writeFileSync('docs/screenshots/soy-gate9/migration-qa.json',JSON.stringify({engine:'PGlite PostgreSQL WASM; isolated schema fixture; no Supabase RLS/PostGIS execution',checks},null,2));console.log(checks);assert(Object.values(checks).every(Boolean));})().catch(e=>{console.error(e);process.exitCode=1});
