// AUTO-GENERATED by @lovable.dev/mcp-js — do not edit. Regenerated by the Vite plugin.
// To take ownership, delete this banner line; the plugin then leaves the file alone.
// supabase function: mcp
// Bundled from src/lib/mcp/index.ts by @lovable.dev/mcp-js.
// src/lib/mcp/index.ts
import { auth, defineMcp } from "npm:@lovable.dev/mcp-js@0.26.2";

// src/lib/mcp/tools/list-events.ts
import { defineTool } from "npm:@lovable.dev/mcp-js@0.26.2";
import { z } from "npm:zod@^3.25.76";

// src/lib/mcp/supabase.ts
import { createClient } from "npm:@supabase/supabase-js@^2.96.0";
function runtimeEnv(name) {
  const runtime = globalThis;
  return runtime.Deno?.env?.get?.(name) ?? runtime.process?.env?.[name];
}
function configuredEnv(names) {
  for (const name of names) {
    const value = runtimeEnv(name)?.trim();
    if (value) return value;
  }
  return void 0;
}
function supabaseProjectUrl() {
  const url = configuredEnv(["SUPABASE_URL", "VITE_SUPABASE_URL"]);
  if (!url) throw new Error("SUPABASE_URL (or VITE_SUPABASE_URL) is required");
  return url;
}
function supabasePublishableKey() {
  const direct = configuredEnv([
    "SUPABASE_PUBLISHABLE_KEY",
    "VITE_SUPABASE_PUBLISHABLE_KEY"
  ]);
  if (direct) return direct;
  const keyset = runtimeEnv("SUPABASE_PUBLISHABLE_KEYS");
  if (keyset) {
    try {
      const parsed = JSON.parse(keyset);
      if (parsed && typeof parsed === "object" && !Array.isArray(parsed)) {
        const keys = parsed;
        const key = [keys.default, ...Object.values(keys)].find((v) => typeof v === "string" && v.trim().startsWith("sb_publishable_"))?.trim();
        if (key) return key;
      }
    } catch {
    }
  }
  const legacy = configuredEnv(["SUPABASE_ANON_KEY", "VITE_SUPABASE_ANON_KEY"]);
  if (legacy) return legacy;
  throw new Error("SUPABASE_PUBLISHABLE_KEY, SUPABASE_PUBLISHABLE_KEYS, or SUPABASE_ANON_KEY is required");
}
function supabaseForUser(ctx) {
  const token = ctx.getToken();
  if (!token) throw new Error("supabaseForUser requires a verified OAuth token");
  return createClient(supabaseProjectUrl(), supabasePublishableKey(), {
    global: { headers: { Authorization: `Bearer ${token}` } },
    auth: { persistSession: false, autoRefreshToken: false }
  });
}
function notAuthenticated() {
  return {
    content: [{ type: "text", text: "N\xE3o autenticado. Conecte-se com sua conta Fenasoja Log." }],
    isError: true
  };
}

// src/lib/mcp/tools/list-events.ts
var list_events_default = defineTool({
  name: "list_events",
  title: "Listar eventos do cronograma",
  description: "Lista eventos da Agenda Fenasoja (cronograma) vis\xEDveis para o usu\xE1rio, com filtros de per\xEDodo, status e busca por t\xEDtulo.",
  inputSchema: {
    from_date: z.string().optional().describe("Data inicial (YYYY-MM-DD)."),
    to_date: z.string().optional().describe("Data final (YYYY-MM-DD)."),
    status: z.string().optional().describe("Status do evento, ex.: planejado, concluido, cancelado."),
    search: z.string().optional().describe("Texto buscado no t\xEDtulo do evento."),
    limit: z.number().int().min(1).max(100).default(20).describe("Quantidade m\xE1xima de eventos.")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ from_date, to_date, status, search, limit }, ctx) => {
    if (!ctx.isAuthenticated()) return notAuthenticated();
    const supabase = supabaseForUser(ctx);
    let query = supabase.from("cronograma_eventos_full").select(
      "id,title,description,status,priority,category,start_date,end_date,start_time,end_time,location,commission_name,responsible_name"
    ).order("start_date", { ascending: true }).limit(limit ?? 20);
    if (from_date) query = query.gte("start_date", from_date);
    if (to_date) query = query.lte("start_date", to_date);
    if (status) query = query.eq("status", status);
    if (search) query = query.ilike("title", `%${search}%`);
    const { data, error } = await query;
    if (error) return { content: [{ type: "text", text: error.message }], isError: true };
    return {
      content: [{ type: "text", text: JSON.stringify(data ?? [], null, 2) }],
      structuredContent: { events: data ?? [] }
    };
  }
});

// src/lib/mcp/tools/get-event.ts
import { defineTool as defineTool2 } from "npm:@lovable.dev/mcp-js@0.26.2";
import { z as z2 } from "npm:zod@^3.25.76";
var get_event_default = defineTool2({
  name: "get_event",
  title: "Detalhar evento",
  description: "Retorna todos os dados de um evento do cronograma, incluindo comiss\xF5es vinculadas, respons\xE1veis e subeventos.",
  inputSchema: { event_id: z2.string().uuid().describe("ID do evento.") },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ event_id }, ctx) => {
    if (!ctx.isAuthenticated()) return notAuthenticated();
    const supabase = supabaseForUser(ctx);
    const { data, error } = await supabase.from("cronograma_eventos_full").select("*").eq("id", event_id).maybeSingle();
    if (error) return { content: [{ type: "text", text: error.message }], isError: true };
    if (!data) {
      return {
        content: [{ type: "text", text: "Evento n\xE3o encontrado ou sem permiss\xE3o de acesso." }],
        isError: true
      };
    }
    return {
      content: [{ type: "text", text: JSON.stringify(data, null, 2) }],
      structuredContent: { event: data }
    };
  }
});

// src/lib/mcp/tools/create-event.ts
import { defineTool as defineTool3 } from "npm:@lovable.dev/mcp-js@0.26.2";
import { z as z3 } from "npm:zod@^3.25.76";
var create_event_default = defineTool3({
  name: "create_event",
  title: "Criar evento no cronograma",
  description: "Cria um novo evento na Agenda Fenasoja para a organiza\xE7\xE3o do usu\xE1rio autenticado.",
  inputSchema: {
    title: z3.string().trim().min(1).describe("T\xEDtulo do evento."),
    start_date: z3.string().describe("Data de in\xEDcio (YYYY-MM-DD)."),
    end_date: z3.string().optional().describe("Data de t\xE9rmino (YYYY-MM-DD)."),
    start_time: z3.string().optional().describe("Hor\xE1rio de in\xEDcio (HH:MM)."),
    end_time: z3.string().optional().describe("Hor\xE1rio de t\xE9rmino (HH:MM)."),
    location: z3.string().optional().describe("Local do evento."),
    description: z3.string().optional().describe("Descri\xE7\xE3o/observa\xE7\xF5es."),
    priority: z3.string().optional().describe("Prioridade do evento.")
  },
  annotations: { readOnlyHint: false, destructiveHint: false, openWorldHint: false },
  handler: async (input, ctx) => {
    if (!ctx.isAuthenticated()) return notAuthenticated();
    const supabase = supabaseForUser(ctx);
    const userId = ctx.getUserId();
    const { data: membership, error: membershipError } = await supabase.from("org_members").select("org_id").eq("user_id", userId).limit(1).maybeSingle();
    if (membershipError) {
      return { content: [{ type: "text", text: membershipError.message }], isError: true };
    }
    if (!membership?.org_id) {
      return {
        content: [{ type: "text", text: "Usu\xE1rio n\xE3o est\xE1 vinculado a nenhuma organiza\xE7\xE3o." }],
        isError: true
      };
    }
    const { data, error } = await supabase.from("cronograma_eventos").insert({
      org_id: membership.org_id,
      created_by_user_id: userId,
      title: input.title,
      start_date: input.start_date,
      end_date: input.end_date ?? null,
      start_time: input.start_time ?? null,
      end_time: input.end_time ?? null,
      location: input.location ?? null,
      description: input.description ?? null,
      priority: input.priority ?? null,
      has_exact_date: true
    }).select("id,title,start_date,status").maybeSingle();
    if (error) return { content: [{ type: "text", text: error.message }], isError: true };
    return {
      content: [{ type: "text", text: JSON.stringify(data, null, 2) }],
      structuredContent: { event: data }
    };
  }
});

// src/lib/mcp/tools/list-transports.ts
import { defineTool as defineTool4 } from "npm:@lovable.dev/mcp-js@0.26.2";
import { z as z4 } from "npm:zod@^3.25.76";
var list_transports_default = defineTool4({
  name: "list_transports",
  title: "Listar transportes",
  description: "Lista transportes da log\xEDstica Fenasoja vis\xEDveis para o usu\xE1rio, com filtro por status e per\xEDodo de in\xEDcio.",
  inputSchema: {
    status: z4.string().optional().describe("Status do transporte: pendente, em_andamento, concluido ou cancelado."),
    from_datetime: z4.string().optional().describe("In\xEDcio m\xEDnimo (ISO 8601)."),
    to_datetime: z4.string().optional().describe("In\xEDcio m\xE1ximo (ISO 8601)."),
    limit: z4.number().int().min(1).max(100).default(20).describe("Quantidade m\xE1xima de registros.")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ status, from_datetime, to_datetime, limit }, ctx) => {
    if (!ctx.isAuthenticated()) return notAuthenticated();
    const supabase = supabaseForUser(ctx);
    let query = supabase.from("transports").select(
      "id,titulo,status,tipo,origem,destino,inicio_em,fim_em,passageiros_qtd,prioridade,observacoes"
    ).order("inicio_em", { ascending: true }).limit(limit ?? 20);
    if (status) query = query.eq("status", status);
    if (from_datetime) query = query.gte("inicio_em", from_datetime);
    if (to_datetime) query = query.lte("inicio_em", to_datetime);
    const { data, error } = await query;
    if (error) return { content: [{ type: "text", text: error.message }], isError: true };
    return {
      content: [{ type: "text", text: JSON.stringify(data ?? [], null, 2) }],
      structuredContent: { transports: data ?? [] }
    };
  }
});

// src/lib/mcp/index.ts
var projectRef = "btfaumhroqtqzxomqorx";
var mcp_default = defineMcp({
  name: "fenasoja-log",
  title: "Fenasoja Log",
  version: "0.1.0",
  instructions: "Ferramentas da Fenasoja Log. Use `list_events`/`get_event` para consultar a Agenda Fenasoja, `create_event` para registrar novos eventos e `list_transports` para acompanhar a log\xEDstica de transportes. Todas as chamadas respeitam as permiss\xF5es do usu\xE1rio conectado.",
  auth: auth.oauth.issuer({
    issuer: `https://${projectRef}.supabase.co/auth/v1`,
    acceptedAudiences: "authenticated"
  }),
  tools: [list_events_default, get_event_default, create_event_default, list_transports_default]
});

// lovable-mcp-supabase-entry.ts
import { createSupabaseHandler } from "npm:@lovable.dev/mcp-js@0.26.2/stacks/supabase";
Deno.serve(createSupabaseHandler(mcp_default, { functionName: "mcp" }));
