BEGIN;
SELECT pg_advisory_xact_lock(hashtext('p7-official-57-september-2026'));
DO $$
DECLARE v_p uuid; v_parent uuid; v_count int; v_bad int; v_frame jsonb; v_lot record; v_x numeric; v_z numeric; v_left numeric; v_top numeric; v_cx numeric; v_cz numeric; v_w numeric; v_d numeric; v_ring jsonb; v_world jsonb; v_center_x numeric; v_center_z numeric; v_width numeric; v_depth numeric; v_n int; v_old jsonb; v_project uuid;
BEGIN
 SELECT id,project_id,metadata->'internalOfficialPlan' INTO v_parent,v_project,v_old FROM public.map_entities WHERE public_identifier='B10' AND classification='PAVILION' AND is_archived=false;
 IF v_parent IS NULL THEN RAISE EXCEPTION 'P7_PARENT_MISSING'; END IF;
 SELECT count(*),count(*) FILTER (WHERE l.status <> 'BLOCKED' OR l.official_area_sqm <> 2.5 OR l.archived_at IS NOT NULL OR e.is_archived OR e.parent_entity_id <> v_parent OR e.metadata->>'layoutRevision' <> '2026.4-p7.1') INTO v_count,v_bad FROM public.commercial_lots l JOIN public.map_entities e ON e.id=l.entity_id WHERE l.project_id=v_project AND l.block='P7';
 IF v_old->>'layoutRevision'='2028.1-p7.57' THEN
  IF v_count<>57 OR (SELECT count(*) FROM public.commercial_lots WHERE project_id=v_project AND block='P7' AND archived_at IS NULL)<>57 THEN RAISE EXCEPTION 'P7_IDEMPOTENCY_CONFLICT'; END IF;
  RETURN;
 END IF;
 IF v_count<>171 OR v_bad<>0 OR v_old->>'layoutRevision'<>'2026.4-p7.1' THEN RAISE EXCEPTION 'P7_LEGACY_INVENTORY_CHANGED'; END IF;
 IF (SELECT count(DISTINCT l.lot_number) FROM public.commercial_lots l WHERE l.project_id=v_project AND l.block='P7')<>171 OR EXISTS (SELECT 1 FROM public.commercial_lots l WHERE l.project_id=v_project AND l.block='P7' AND (l.public_identifier <> 'B10-M'||lpad(l.lot_number,3,'0') OR l.lot_number !~ '^[0-9]{2,3}$' OR l.lot_number::int NOT BETWEEN 1 AND 171)) THEN RAISE EXCEPTION 'P7_NUMBERING_CHANGED'; END IF;
 IF EXISTS(SELECT 1 FROM public.commercial_lots l WHERE l.project_id=v_project AND l.block='P7' AND (EXISTS(SELECT 1 FROM public.lot_sales x WHERE x.lot_id=l.id) OR EXISTS(SELECT 1 FROM public.lot_reservations x WHERE x.lot_id=l.id) OR EXISTS(SELECT 1 FROM public.lot_negotiations x WHERE x.lot_id=l.id) OR EXISTS(SELECT 1 FROM public.lot_contracts x WHERE x.lot_id=l.id) OR EXISTS(SELECT 1 FROM public.lot_sale_order_items x WHERE x.lot_id=l.id) OR EXISTS(SELECT 1 FROM public.commercial_lot_price_overrides x WHERE x.lot_id=l.id) OR EXISTS(SELECT 1 FROM public.lot_status_history x WHERE x.lot_id=l.id))) THEN RAISE EXCEPTION 'P7_COMMERCIAL_RECONCILIATION_REQUIRED'; END IF;
 SELECT e.metadata->'projectionFrame' INTO v_frame FROM public.map_entities e WHERE e.parent_entity_id=v_parent AND e.public_identifier='B10-M001' AND NOT e.is_archived;
 IF v_frame IS NULL THEN RAISE EXCEPTION 'P7_PROJECTION_MISSING'; END IF;
 v_center_x:=(v_frame->>'centerX')::numeric; v_center_z:=(v_frame->>'centerZ')::numeric; v_width:=(v_frame->>'width')::numeric; v_depth:=(v_frame->>'depth')::numeric;
 IF v_width<=0 OR v_depth<=0 THEN RAISE EXCEPTION 'P7_PROJECTION_INVALID'; END IF;
 FOR v_lot IN SELECT l.id,l.entity_id,l.lot_number::int n,l.status,e.metadata FROM public.commercial_lots l JOIN public.map_entities e ON e.id=l.entity_id WHERE l.project_id=v_project AND l.block='P7' ORDER BY l.lot_number::int FOR UPDATE OF l LOOP
  v_n:=v_lot.n;
  IF v_n>57 THEN
   UPDATE public.commercial_lots SET archived_at=transaction_timestamp(),status='UNAVAILABLE',updated_at=transaction_timestamp() WHERE id=v_lot.id;
   UPDATE public.map_entities SET is_archived=true,metadata=metadata||jsonb_build_object('archivedByRevision','2028.1-p7.57'),updated_at=transaction_timestamp() WHERE id=v_lot.entity_id;
   CONTINUE;
  END IF;
  IF v_n<=4 THEN v_left:=3.7+(v_n-1)*3; v_top:=0.2;
  ELSIF v_n<=15 THEN v_left:=16.4+(v_n-5)*3; v_top:=0.2;
  ELSIF v_n<=29 THEN v_left:=3.95+(v_n-16)*3; v_top:=6.65;
  ELSIF v_n<=43 THEN v_left:=3.95+(43-v_n)*3; v_top:=9.15;
  ELSIF v_n<=49 THEN v_left:=0.2+(v_n-44)*3; v_top:=15.6;
  ELSE v_left:=25.7+(v_n-50)*3; v_top:=15.6; END IF;
  v_cx:=(v_left+1.5)/49.9; v_cz:=(v_top+1.25)/18.3; v_w:=3/49.9; v_d:=2.5/18.3;
  v_ring:=jsonb_build_array(jsonb_build_array(v_left/49.9,v_top/18.3),jsonb_build_array((v_left+3)/49.9,v_top/18.3),jsonb_build_array((v_left+3)/49.9,(v_top+2.5)/18.3),jsonb_build_array(v_left/49.9,(v_top+2.5)/18.3),jsonb_build_array(v_left/49.9,v_top/18.3));
  SELECT jsonb_agg(jsonb_build_array(v_center_x+((point->>0)::numeric-.5)*v_width,v_center_z+((point->>1)::numeric-.5)*v_depth) ORDER BY ordinality) INTO v_world FROM jsonb_array_elements(v_ring) WITH ORDINALITY AS t(point,ordinality);
  UPDATE public.map_entities SET name='Box '||lpad(v_n::text,2,'0'),verification_status='VERIFIED',metadata=(metadata-ARRAY['sourceDiscrepancy','areaBackfill'])||jsonb_build_object('source','Ajuste_Pav07.pdf (setembro/2026)','layoutRevision','2028.1-p7.57','sourceRevision','2028.1','sourceInterpretation','official-reference-runs','moduleNumber',v_n,'lotNumber',lpad(v_n::text,2,'0'),'sortOrder',v_n,'areaM2',7.5,'officialMeasurements',true,'normalizedFootprint',jsonb_build_object('centerX',v_cx,'centerZ',v_cz,'width',v_w,'depth',v_d),'normalizedFootprintPolygon',v_ring,'normalizedLabelAnchor',jsonb_build_array(v_cx,v_cz),'labelAnchor',jsonb_build_array(v_center_x+(v_cx-.5)*v_width,v_center_z+(v_cz-.5)*v_depth),'renderParts',jsonb_build_array(jsonb_build_object('centerX',v_cx,'centerZ',v_cz,'width',v_w,'depth',v_d)),'projectionFrame',v_frame,'group',CASE WHEN v_n BETWEEN 16 AND 43 THEN 'central-pair' WHEN v_n<=15 THEN 'perimeter-north' ELSE 'perimeter-south' END,'cluster',CASE WHEN v_n<=15 THEN 'north-01-15' WHEN v_n<=43 THEN 'central-16-43' ELSE 'south-44-57' END,'sequenceOrientation',CASE WHEN v_n BETWEEN 30 AND 43 THEN 'x-decreasing' ELSE 'x-increasing' END),updated_at=transaction_timestamp() WHERE id=v_lot.entity_id;
  UPDATE public.commercial_lots SET display_name='Box '||lpad(v_n::text,2,'0'),status='AVAILABLE',official_area_sqm=7.5,calculated_area_sqm=7.5,frontage_meters=3,depth_meters=2.5,area_validation_status='VALIDATED',updated_at=transaction_timestamp() WHERE id=v_lot.id;
  UPDATE public.map_entity_geometries SET geometry=jsonb_build_object('type','Polygon','coordinates',jsonb_build_array(v_world)),version=version+1,change_reason='Croqui oficial setembro/2026: 57 boxes de 7,50 m²',updated_at=transaction_timestamp() WHERE entity_id=v_lot.entity_id AND is_current=true;
 END LOOP;
  UPDATE public.map_entities SET name='Pavilhão 7 — Agricultura Familiar / Agroindústrias',metadata=(metadata - 'internalPlanRuns'::text)||jsonb_build_object('internalOfficialPlan',((metadata->'internalOfficialPlan') - 'sourceDiscrepancy'::text)||jsonb_build_object('officialName','Pavilhão 7 — Agricultura Familiar / Agroindústrias','layoutRevision','2028.1-p7.57','source','Ajuste_Pav07.pdf (setembro/2026)','moduleCount',57,'sourceDeclaredModuleCount',57,'totalAreaM2',917,'modularAreaM2',427.5,'nominalGeometricAreaM2',427.5),'internalPlanRuns',(SELECT jsonb_agg(jsonb_build_object('id',t.id,'label',t.label,'numberRange',jsonb_build_array(t.first,t.last),'group',t.grp,'cluster',t.cluster,'role',t.role,'orientation','north-south','sequenceOrientation',t.direction,'sourcePrecision','official-metric','normalizedFootprint',jsonb_build_object('centerX',(t.left_m+t.count_n*1.5)/49.9,'centerZ',(t.top_m+1.25)/18.3,'width',t.count_n*3/49.9,'depth',2.5/18.3)) ORDER BY t.first) FROM (VALUES ('north-west-01-04','Boxes 01–04',1,4,3.7::numeric,0.2::numeric,4,'perimeter-north','north-01-15','perimeter','x-increasing'),('north-east-05-15','Boxes 05–15',5,15,16.4,0.2,11,'perimeter-north','north-01-15','perimeter','x-increasing'),('central-north-16-29','Boxes 16–29',16,29,3.95,6.65,14,'central-pair','central-16-43','island','x-increasing'),('central-south-30-43','Boxes 43–30',30,43,3.95,9.15,14,'central-pair','central-16-43','island','x-decreasing'),('south-west-44-49','Boxes 44–49',44,49,0.2,15.6,6,'perimeter-south','south-44-57','perimeter','x-increasing'),('south-east-50-57','Boxes 50–57',50,57,25.7,15.6,8,'perimeter-south','south-44-57','perimeter','x-increasing')) AS t(id,label,first,last,left_m,top_m,count_n,grp,cluster,role,direction))),updated_at=transaction_timestamp() WHERE id=v_parent;
 IF (SELECT count(*) FROM public.commercial_lots WHERE project_id=v_project AND block='P7' AND archived_at IS NULL)<>57 OR (SELECT sum(official_area_sqm) FROM public.commercial_lots WHERE project_id=v_project AND block='P7' AND archived_at IS NULL)<>427.5 THEN RAISE EXCEPTION 'P7_POSTCHECK_FAILED'; END IF;
END $$;
INSERT INTO public.commercial_price_rules(exercise,stage,scope_type,pavilion_identifier,range_start,range_end,price_per_sqm,priority,label,source,notes)
SELECT 2028,'RENOVACAO','MODULE_RANGE','P7',v.start_n,v.end_n,344,100,v.label,'AUTORIZACAO_USUARIO_2026_09_26','R$ 344,00/m² confirmado pelo usuário; PDF de políticas anterior mostra traço para P7. Sem 2ª etapa.' FROM (VALUES (1,47,'Pavilhão 7 — SDR, boxes 01–47'),(48,57,'Pavilhão 7 — Fenasoja, boxes 48–57')) v(start_n,end_n,label) WHERE NOT EXISTS(SELECT 1 FROM public.commercial_price_rules r WHERE r.exercise=2028 AND r.stage='RENOVACAO' AND r.pavilion_identifier='P7' AND r.range_start=v.start_n AND r.range_end=v.end_n);
COMMIT;