CREATE OR REPLACE VIEW public.commercial_lot_pricing_2028 AS
WITH lot_base AS (
 SELECT l.id lot_id,l.project_id,l.public_identifier,CASE WHEN l.block ~ '^P[0-9]+$' THEN NULL::text ELSE l.block END block,l.status,l.official_area_sqm,l.area_validation_status,NULLIF(regexp_replace(COALESCE(l.lot_number,''),'\D','','g'),'')::int lot_num,CASE WHEN l.block ~ '^P[0-9]+$' THEN l.block ELSE NULL::text END pavilion,COALESCE(ca.classification,'NOT_AUDITED') corner_status,COALESCE(ca.classification,'')='CORNER_CONFIRMED' corner_confirmed, CASE WHEN e.metadata->>'pricingGroup'='quadra-r-01-12' AND l.block='R' AND l.public_identifier='EXPORURAL-AREA-56878' THEN 1 ELSE NULL END pricing_group_num FROM public.commercial_lots l JOIN public.map_entities e ON e.id=l.entity_id LEFT JOIN public.commercial_lot_corner_audit ca ON ca.lot_id=l.id WHERE l.archived_at IS NULL AND NOT e.is_archived
), matched AS (
 SELECT b.lot_id,r.stage,r.id rule_id,r.label,CASE WHEN b.pricing_group_num=1 AND r.stage='SEGUNDA_ETAPA' AND r.block='R' AND r.range_start=1 AND r.range_end=12 THEN 30.25::numeric ELSE r.price_per_sqm END price_per_sqm,r.priority,rank() OVER(PARTITION BY b.lot_id,r.stage ORDER BY r.priority DESC) rnk FROM lot_base b JOIN public.commercial_price_rules r ON r.is_active AND r.exercise=2028 AND r.scope_type<>'EXCLUSION' AND (r.project_id IS NULL OR r.project_id=b.project_id) AND (r.pavilion_identifier IS NULL OR r.pavilion_identifier=b.pavilion) AND (r.block IS NULL OR r.block=b.block) AND (r.pavilion_identifier IS NOT NULL OR r.block IS NOT NULL) AND (r.range_start IS NULL OR (COALESCE(b.pricing_group_num,b.lot_num) IS NOT NULL AND COALESCE(b.pricing_group_num,b.lot_num)>=r.range_start AND COALESCE(b.pricing_group_num,b.lot_num)<=r.range_end)) AND (r.is_corner IS NULL OR r.is_corner=b.corner_confirmed)
), top_matches AS (
 SELECT lot_id,stage,rule_id,label,price_per_sqm,count(*) OVER(PARTITION BY lot_id,stage) tie_count FROM matched WHERE rnk=1
), resolved AS (
 SELECT b.*,ren.rule_id renovacao_rule_id,ren.label renovacao_rule_label,ren.price_per_sqm rule_ren_ppsqm,ren.tie_count ren_tie,seg.rule_id segunda_rule_id,seg.label segunda_rule_label,seg.price_per_sqm rule_seg_ppsqm,seg.tie_count seg_tie,ovr.total ren_override,ovs.total seg_override FROM lot_base b LEFT JOIN top_matches ren ON ren.lot_id=b.lot_id AND ren.stage='RENOVACAO' LEFT JOIN top_matches seg ON seg.lot_id=b.lot_id AND seg.stage='SEGUNDA_ETAPA' LEFT JOIN public.commercial_lot_price_overrides ovr ON ovr.lot_id=b.lot_id AND ovr.stage='RENOVACAO' LEFT JOIN public.commercial_lot_price_overrides ovs ON ovs.lot_id=b.lot_id AND ovs.stage='SEGUNDA_ETAPA'
), calc AS (
 SELECT r.*,CASE WHEN COALESCE(official_area_sqm,0)<=0 OR COALESCE(ren_tie,0)<>1 THEN NULL ELSE round(official_area_sqm*rule_ren_ppsqm,2) END ren_default,CASE WHEN COALESCE(official_area_sqm,0)<=0 OR COALESCE(seg_tie,0)<>1 THEN NULL ELSE round(official_area_sqm*rule_seg_ppsqm,2) END seg_default FROM resolved r
)
SELECT lot_id,project_id,public_identifier,pavilion,block,lot_num,status,corner_status,corner_confirmed,official_area_sqm,area_validation_status,renovacao_rule_id,CASE WHEN ren_override IS NOT NULL THEN 'Valor manual' ELSE renovacao_rule_label END renovacao_rule_label,(CASE WHEN ren_override IS NOT NULL THEN CASE WHEN COALESCE(official_area_sqm,0)>0 THEN round(ren_override/official_area_sqm,2) ELSE NULL END ELSE rule_ren_ppsqm END)::numeric(12,2) renovacao_price_per_sqm,segunda_rule_id,CASE WHEN seg_override IS NOT NULL THEN 'Valor manual' ELSE segunda_rule_label END segunda_rule_label,(CASE WHEN seg_override IS NOT NULL THEN CASE WHEN COALESCE(official_area_sqm,0)>0 THEN round(seg_override/official_area_sqm,2) ELSE NULL END ELSE rule_seg_ppsqm END)::numeric(12,2) segunda_price_per_sqm,COALESCE(ren_override,ren_default) renovacao_total,COALESCE(seg_override,seg_default) segunda_total,CASE WHEN ren_override IS NOT NULL AND seg_override IS NOT NULL THEN 'OK' WHEN COALESCE(official_area_sqm,0)<=0 THEN 'SEM_AREA' WHEN (ren_override IS NULL AND COALESCE(ren_tie,0)>1) OR (seg_override IS NULL AND COALESCE(seg_tie,0)>1) THEN 'REGRA_AMBIGUA' WHEN pavilion='P7' AND COALESCE(ren_override,ren_default) IS NOT NULL THEN 'OK' WHEN (ren_override IS NULL AND renovacao_rule_id IS NULL) OR (seg_override IS NULL AND segunda_rule_id IS NULL) THEN 'SEM_REGRA' ELSE 'OK' END resolution_status,ren_default renovacao_default_total,seg_default segunda_default_total,(ren_override IS NOT NULL) renovacao_is_manual,(seg_override IS NOT NULL) segunda_is_manual FROM calc;