CREATE OR REPLACE VIEW public.commercial_lot_pricing_2028 AS
WITH lot_base AS (
 SELECT l.id lot_id,l.project_id,l.public_identifier,CASE WHEN l.block ~ '^P[0-9]+$' THEN NULL::text ELSE l.block END block,l.status,l.official_area_sqm,l.area_validation_status,NULLIF(regexp_replace(COALESCE(l.lot_number,''),'\D','','g'),'')::int lot_num,CASE WHEN l.block ~ '^P[0-9]+$' THEN l.block ELSE NULL::text END pavilion,COALESCE(ca.classification,'NOT_AUDITED') corner_status,COALESCE(ca.classification,'')='CORNER_CONFIRMED' corner_confirmed FROM public.commercial_lots l JOIN public.map_entities e ON e.id=l.entity_id LEFT JOIN public.commercial_lot_corner_audit ca ON ca.lot_id=l.id WHERE l.archived_at IS NULL AND NOT e.is_archived
), matched AS (
 SELECT b.lot_id,r.stage,r.id rule_id,r.label,r.price_per_sqm,r.priority,rank() OVER(PARTITION BY b.lot_id,r.stage ORDER BY r.priority DESC) rnk FROM lot_base b JOIN public.commercial_price_rules r ON r.is_active AND r.exercise=2028 AND r.scope_type<>'EXCLUSION' AND (r.project_id IS NULL OR r.project_id=b.project_id) AND (r.pavilion_identifier IS NULL OR r.pavilion_identifier=b.pavilion) AND (r.block IS NULL OR r.block=b.block) AND (r.pavilion_identifier IS NOT NULL OR r.block IS NOT NULL) AND (r.range_start IS NULL OR (b.lot_num IS NOT NULL AND b.lot_num>=r.range_start AND b.lot_num<=r.range_end)) AND (r.is_corner IS NULL OR r.is_corner=b.corner_confirmed)
), top_matches AS (
 SELECT lot_id,stage,rule_id,label,price_per_sqm,count(*) OVER(PARTITION BY lot_id,stage) tie_count FROM matched WHERE rnk=1
), resolved AS (
 SELECT b.*,ren.rule_id renovacao_rule_id,ren.label renovacao_rule_label,ren.price_per_sqm rule_ren_ppsqm,ren.tie_count ren_tie,seg.rule_id segunda_rule_id,seg.label segunda_rule_label,seg.price_per_sqm rule_seg_ppsqm,seg.tie_count seg_tie,ovr.total ren_override,ovs.total seg_override FROM lot_base b LEFT JOIN top_matches ren ON ren.lot_id=b.lot_id AND ren.stage='RENOVACAO' LEFT JOIN top_matches seg ON seg.lot_id=b.lot_id AND seg.stage='SEGUNDA_ETAPA' LEFT JOIN public.commercial_lot_price_overrides ovr ON ovr.lot_id=b.lot_id AND ovr.stage='RENOVACAO' LEFT JOIN public.commercial_lot_price_overrides ovs ON ovs.lot_id=b.lot_id AND ovs.stage='SEGUNDA_ETAPA'
), calc AS (
 SELECT r.*,CASE WHEN COALESCE(official_area_sqm,0)<=0 OR COALESCE(ren_tie,0)<>1 THEN NULL ELSE round(official_area_sqm*rule_ren_ppsqm,2) END ren_default,CASE WHEN COALESCE(official_area_sqm,0)<=0 OR COALESCE(seg_tie,0)<>1 THEN NULL ELSE round(official_area_sqm*rule_seg_ppsqm,2) END seg_default FROM resolved r
)
SELECT lot_id,project_id,public_identifier,pavilion,block,lot_num,status,corner_status,corner_confirmed,official_area_sqm,area_validation_status,renovacao_rule_id,CASE WHEN ren_override IS NOT NULL THEN 'Valor manual' ELSE renovacao_rule_label END renovacao_rule_label,(CASE WHEN ren_override IS NOT NULL THEN CASE WHEN COALESCE(official_area_sqm,0)>0 THEN round(ren_override/official_area_sqm,2) ELSE NULL END ELSE rule_ren_ppsqm END)::numeric(12,2) renovacao_price_per_sqm,segunda_rule_id,CASE WHEN seg_override IS NOT NULL THEN 'Valor manual' ELSE segunda_rule_label END segunda_rule_label,(CASE WHEN seg_override IS NOT NULL THEN CASE WHEN COALESCE(official_area_sqm,0)>0 THEN round(seg_override/official_area_sqm,2) ELSE NULL END ELSE rule_seg_ppsqm END)::numeric(12,2) segunda_price_per_sqm,COALESCE(ren_override,ren_default) renovacao_total,COALESCE(seg_override,seg_default) segunda_total,CASE WHEN ren_override IS NOT NULL AND seg_override IS NOT NULL THEN 'OK' WHEN COALESCE(official_area_sqm,0)<=0 THEN 'SEM_AREA' WHEN (ren_override IS NULL AND COALESCE(ren_tie,0)>1) OR (seg_override IS NULL AND COALESCE(seg_tie,0)>1) THEN 'REGRA_AMBIGUA' WHEN pavilion='P7' AND COALESCE(ren_override,ren_default) IS NOT NULL THEN 'OK' WHEN (ren_override IS NULL AND renovacao_rule_id IS NULL) OR (seg_override IS NULL AND segunda_rule_id IS NULL) THEN 'SEM_REGRA' ELSE 'OK' END resolution_status,ren_default renovacao_default_total,seg_default segunda_default_total,(ren_override IS NOT NULL) renovacao_is_manual,(seg_override IS NOT NULL) segunda_is_manual FROM calc;
CREATE OR REPLACE VIEW public.commercial_sale_eligibility WITH (security_invoker=on) AS WITH hist AS (
 SELECT lot_id,count(*) entries,count(*) FILTER(WHERE reason IS DISTINCT FROM 'Lote numerado importado da referência oficial 2026.3; validação comercial pendente.') commercial_entries FROM public.lot_status_history GROUP BY lot_id
), base AS (
 SELECT l.id lot_id,l.project_id,l.public_identifier,l.block,l.status,l.official_area_sqm,p.resolution_status,(l.block='P7' AND p.renovacao_total IS NULL) is_unpriced_pavilion,EXISTS(SELECT 1 FROM public.lot_sales s WHERE s.lot_id=l.id AND COALESCE(s.status,'ACTIVE')<>'REVERTED') has_active_sale,EXISTS(SELECT 1 FROM public.lot_reservations r WHERE r.lot_id=l.id AND r.status='ACTIVE') has_active_reservation,EXISTS(SELECT 1 FROM public.lot_negotiations n WHERE n.lot_id=l.id AND n.status='ACTIVE') has_active_negotiation,EXISTS(SELECT 1 FROM public.lot_contracts c WHERE c.lot_id=l.id AND c.is_active) has_active_contract,l.archived_at,COALESCE(h.commercial_entries,0) commercial_entries FROM public.commercial_lots l LEFT JOIN hist h ON h.lot_id=l.id LEFT JOIN public.commercial_lot_pricing_2028 p ON p.lot_id=l.id
) SELECT lot_id,project_id,public_identifier,block,status,official_area_sqm,resolution_status,is_unpriced_pavilion,has_active_sale,has_active_reservation,has_active_negotiation,has_active_contract,CASE WHEN status IN ('AVAILABLE','RESERVED','IN_NEGOTIATION') THEN 'COMMERCIAL_OPEN' WHEN status='BLOCKED' AND commercial_entries=0 THEN 'TECHNICAL_BLOCK' WHEN status='BLOCKED' THEN 'COMMERCIAL_BLOCK' ELSE 'CLOSED' END status_origin,CASE WHEN archived_at IS NOT NULL THEN 'ARQUIVADO' WHEN official_area_sqm IS NULL OR official_area_sqm<=0 THEN 'SEM_AREA_OFICIAL' WHEN resolution_status IS DISTINCT FROM 'OK' THEN 'SEM_PRECO_2028' WHEN has_active_sale THEN 'VENDA_ATIVA' WHEN has_active_reservation THEN 'RESERVA_ATIVA' WHEN has_active_negotiation THEN 'NEGOCIACAO_ATIVA' WHEN has_active_contract THEN 'CONTRATO_ATIVO' WHEN status IN ('AVAILABLE','RESERVED','IN_NEGOTIATION') OR (status='BLOCKED' AND commercial_entries=0) THEN NULL WHEN status='BLOCKED' THEN 'BLOQUEIO_COMERCIAL_EXPLICITO' ELSE 'STATUS_NAO_VENDAVEL' END ineligible_reason,(archived_at IS NULL AND official_area_sqm>0 AND resolution_status='OK' AND NOT has_active_sale AND NOT has_active_reservation AND NOT has_active_negotiation AND NOT has_active_contract AND (status IN ('AVAILABLE','RESERVED','IN_NEGOTIATION') OR (status='BLOCKED' AND commercial_entries=0))) is_sellable FROM base;
CREATE OR REPLACE FUNCTION public.set_lot_price_override(p_lot_id uuid,p_stage text,p_total numeric) RETURNS jsonb LANGUAGE plpgsql SECURITY DEFINER SET search_path=public,pg_temp AS $$ DECLARE v_org uuid;v_project uuid;v_before numeric;v_uid uuid:=auth.uid();v_role text;v_name text; BEGIN IF v_uid IS NULL THEN RAISE EXCEPTION 'AUTH_REQUIRED'; END IF; IF p_stage NOT IN ('RENOVACAO','SEGUNDA_ETAPA') THEN RAISE EXCEPTION 'INVALID_STAGE'; END IF; IF p_total IS NULL OR p_total<0 OR p_total>100000000 OR p_total<>round(p_total,2) THEN RAISE EXCEPTION 'INVALID_VALUE'; END IF; SELECT p.org_id,l.project_id INTO v_org,v_project FROM public.commercial_lots l JOIN public.map_projects p ON p.id=l.project_id WHERE l.id=p_lot_id AND l.archived_at IS NULL; IF v_org IS NULL THEN RAISE EXCEPTION 'LOT_NOT_FOUND'; END IF; v_role:=public.get_user_org_role(v_uid,v_org); IF NOT(v_role IN ('admin','gestor') OR public.has_role(v_uid,'admin') OR public.map_has_explicit_capability(v_org,'map.edit') OR public.map_has_explicit_capability(v_org,'map.manage_lots') OR public.map_has_explicit_capability(v_org,'map.admin') OR public.map_has_explicit_capability(v_org,'full_access')) THEN RAISE EXCEPTION 'FORBIDDEN'; END IF; SELECT full_name INTO v_name FROM public.profiles WHERE user_id=v_uid LIMIT 1; SELECT CASE WHEN p_stage='RENOVACAO' THEN renovacao_total ELSE segunda_total END INTO v_before FROM public.commercial_lot_pricing_2028 WHERE lot_id=p_lot_id; INSERT INTO public.commercial_lot_price_overrides(lot_id,stage,total,previous_total,updated_by) VALUES(p_lot_id,p_stage,round(p_total,2),v_before,v_uid) ON CONFLICT(lot_id,stage) DO UPDATE SET total=EXCLUDED.total,previous_total=v_before,updated_by=v_uid,updated_at=now(); UPDATE public.commercial_lots SET updated_at=now() WHERE id=p_lot_id; INSERT INTO public.map_activity_logs(org_id,project_id,lot_id,action,before_state,after_state,actor_user_id) VALUES(v_org,v_project,p_lot_id,'price_override_set',jsonb_build_object('stage',p_stage,'total',v_before),jsonb_build_object('stage',p_stage,'total',round(p_total,2),'actor_name',v_name),v_uid); RETURN jsonb_build_object('lot_id',p_lot_id,'stage',p_stage,'previous_total',v_before,'total',round(p_total,2)); END $$;